Python does not have a generic Error
When running the getting started with Drive notebook, without being
logged in to Drive I got a NameError:

NameError: name 'Error' is not defined.

Since the accompanying message indicates not being logged in, it seems
appropriate to raise a permissions error.